exports.VALID_EMAIL = 'Enter a valid email';
exports.VALID_PASSWORD = 'Enter a valid password';
exports.VALID_USERNAME = 'Enter a username'
exports.ISREQUIRED = 'This field is required'
exports.MIN_CHARACTERS = 'Need at least 8 characters'
exports.MIN_CHARACTERS_USERNAME = 'Need at least 5 characters'
exports.MAX_CHARACTERS_USERNAME = 'Maximum of 20 characters'
exports.USER_EXISTS = 'Username or email already exists'
exports.USER_NOT_CREATED = 'User was not created'
exports.PASSWORD_NOT_MATCHED = 'The passwords No match'
exports.USER_NOT_EXISTS = 'User not exists'
exports.WELCOME = 'Welcome User'
exports.NO_CREDENTIALS = 'You have not the credentials, Login for it'
exports.ERROR = 'An error has occurred'